### ISSUE TITLE
[лр. 1] Отсутствуют проверки на корректное архивирование и разархивирование в `main.c`

### ISSUE THREAD

**Issue by DieTime** [Danya4Art/os_lr#5]

**Comment by Danya4Art** [comment]
Изменил возвращаемый из main.c код в зависимости от успеха архивирования/разархивирования, но проверкой это назвать тяжело. Написать unit-тесты?

**Comment by DieTime** [comment]
Внутри функций есть логирование ошибки, так что я думаю, что все ок и возврата результата функции будет достаточно.
